name       : gopls
version    : 0.12.4
release    : 2
source     :
    - https://github.com/golang/tools/archive/refs/tags/gopls/v0.12.4.tar.gz : 746b0e1942c028c62fd8c114242a024faed19009ac64180f2cbfc9480fd45544
license    : BSD-3-Clause
component  : programming.tools
summary    : Go language server (LSP)
description: |
    gopls (pronounced "Go please") is the official Go language server developed by the Go team. It provides IDE features to any LSP-compatible editor.
networking : yes
builddeps  :
    - golang
environment: |
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"
    cd gopls
build      : |
    go build -o gopls
install    : |
    install -Dm00755 gopls -t $installdir/usr/bin/
